[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [ 
    "leetcode", "sql",
]

[workspace.dependencies]
leetcode = { path = "./leetcode" }
sql = { path = "./sql" }

