[package]
name = "sql"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version="1.0.200",features = ["derive"] }
serde_bytes = "0.11.14"
regex = "1.10.4"

[dev-dependencies]
serde_json = "1.0.117"
goldenscript = "0.7.0"
test_each_file = "0.3.2"